cooldowns:
  radiomessagecooldown: 2000
distances:
  distancefromcelltower: 150
  distancefromradiotower: 150
  distanceforwhisperimg: 10
  distancefortalking: 50
  distanceforyelling: 1000
  distanceforbreakingupfactor: 0.7
features:
  radio: true
  realisticchat: true
  cellphones: true
  loreitems: false
loreitemname:
  phone: §bPhone
  